[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[browser]
serverAddress = "0.0.0.0"
serverPort = 7860
gatherUsageStats = false

[server]
address = "0.0.0.0"
port = 7860